"""Studio-only renderer adapters built on top of the installed TenTags model."""

from copy import deepcopy
from urllib.parse import unquote, urlparse

import tentags


def _decoded_image_model(model):
    """Return a model copy whose local image paths contain real spaces."""

    result = deepcopy(model)
    for row in result.cells:
        for cell in row:
            for image in cell.images:
                source = unquote(str(image.get("src", "")))
                if source.lower().startswith("file://"):
                    parsed = urlparse(source)
                    source = parsed.path
                    if parsed.netloc:
                        source = f"//{parsed.netloc}{source}"
                    if len(source) >= 3 and source[0] == "/" and source[2] == ":":
                        source = source[1:]
                image["src"] = source
    return result


def render_xlsx_with_images(model, output):
    """Render XLSX after decoding local paths generated by TenTags Studio."""

    tentags.render_xlsx(_decoded_image_model(model), output)


def render_pdf_with_images(model, output, settings=None):
    """Delegate PDF images to TenTags 2.1.14 after decoding local paths."""

    tentags.render_pdf(
        _decoded_image_model(model),
        output,
        settings=settings,
    )
